# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Team.delete_all
User.delete_all
Matchup.delete_all

Team.create([
  { name: "Arizona Cardinals", alias: "ARI", palette: "#9B2743", image_url: "ARI.png" },
  { name: "Atlanta Falcons", alias: "ATL", palette: "#BD0D18", image_url: "ATL.png" },
  { name: "Baltimore Ravens", alias: "BAL", palette: "#280353", image_url: "BAL.png" },
  { name: "Buffalo Bills", alias: "BUF", palette: "#00338D", image_url: "BUF.png" },
  { name: "Carolina Panthers", alias: "CAR", palette: "#0088CE", image_url: "CAR.png" },
  { name: "Chicago Bears", alias: "CHI", palette: "#03202F", image_url: "CHI.png" },
  { name: "Cincinnati Bengals", alias: "CIN", palette: "#FB4F14", image_url: "CIN.gif" },
  { name: "Cleveland Browns", alias: "CLE", palette: "#FE3C00", image_url: "CLE.png" },
  { name: "Dallas Cowboys", alias: "DAL", palette: "#0D254C", image_url: "DAL.gif" },
  { name: "Denver Broncos", alias: "DEN", palette: "#FB4F14", image_url: "DEN.png" },
  { name: "Detroit Lions", alias: "DET", palette: "#006DB0", image_url: "DET.png" },
  { name: "Green Bay Packers", alias: "GB", palette: "#203731", image_url: "GB.png" },
  { name: "Houston Texans", alias: "HOU", palette: "#02253A", image_url: "HOU.png" },
  { name: "Indianapolis Colts", alias: "IND", palette: "#003B7B", image_url: "IND.png" },
  { name: "Jacksonville Jaguars", alias: "JAC", palette: "#006778", image_url: "JAC.png" },
  { name: "Kansas City Chiefs", alias: "KC", palette: "#B20032", image_url: "KC.png" },
  { name: "Los Angeles Rams", alias: "LA", palette: "#13264B", image_url: "LA.png" },
  { name: "Miami Dolphins", alias: "MIA", palette: "#008D97", image_url: "MIA.png" },
  { name: "Minnesota Vikings", alias: "MIN", palette: "#3B0160", image_url: "MIN.png" },
  { name: "New England Patriots", alias: "NE", palette: "#0D254C", image_url: "NE.gif" },
  { name: "New Orleans Saints", alias: "NO", palette: "#D2B887", image_url: "NO.gif" },
  { name: "New York Giants", alias: "NYG", palette: "#192F6B", image_url: "NYG.gif" },
  { name: "New York Jets", alias: "NYJ", palette: "#0C371D", image_url: "NYJ.gif" },
  { name: "Oakland Raiders", alias: "OAK", palette: "#C4C8CB", image_url: "OAK.gif" },
  { name: "Philadelphia Eagles", alias: "PHI", palette: "#003B48", image_url: "PHI.png" },
  { name: "Pittsburgh Steelers", alias: "PIT", palette: "#FFB612", image_url: "PIT.png" },
  { name: "San Diego Chargers", alias: "SD", palette: "#0072CE", image_url: "SD.png" },
  { name: "San Francisco 49ers", alias: "SF", palette: "#AF1E2C", image_url: "SF.gif" },
  { name: "Seattle Seahawks", alias: "SEA", palette: "#002244", image_url: "SEA.png" },
  { name: "Tampa Bay Buccaneers", alias: "TB", palette: "#D60A0B", image_url: "TB.png" },
  { name: "Tennessee Titans", alias: "TEN", palette: "#648FCC", image_url: "TEN.png" },
  { name: "Washington Redskins", alias: "WAS", palette: "#773141", image_url: "WAS.gif" }
])

User.create([
  { name: "Michael Woo", email: "michael@test.com", password_hash: "12345", subtotal: 0, total: 0, team_id: 23, admin: false},
  { name: "Ricky Bobby", email: "ricky@test.com", password_hash: "12345", subtotal: 0, total: 0, team_id: 10, admin: false}
])


Matchup.create([
  { week:1, home_team_id:Team.all[14], away_team_id:Team.all[11]},
  { week:1, home_team_id:Team.all[30], away_team_id:Team.all[18]},
  { week:1, home_team_id:Team.all[12], away_team_id:Team.all[5]},
  { week:1, home_team_id:Team.all[8], away_team_id:Team.all[21]},
  { week:1, home_team_id:Team.all[1], away_team_id:Team.all[29]},
  { week:1, home_team_id:Team.all[2], away_team_id:Team.all[3]},
  { week:1, home_team_id:Team.all[9], away_team_id:Team.all[4]},
  { week:1, home_team_id:Team.all[0], away_team_id:Team.all[19]},
  { week:1, home_team_id:Team.all[13], away_team_id:Team.all[10]},
  { week:1, home_team_id:Team.all[22], away_team_id:Team.all[6]},
  { week:1, home_team_id:Team.all[31], away_team_id:Team.all[25]},
  { week:1, home_team_id:Team.all[20], away_team_id:Team.all[23]},
  { week:1, home_team_id:Team.all[27], away_team_id:Team.all[16]},
  { week:1, home_team_id:Team.all[24], away_team_id:Team.all[7]},
  { week:1, home_team_id:Team.all[15], away_team_id:Team.all[26]},
  { week:1, home_team_id:Team.all[28], away_team_id:Team.all[17]},
  { week:2, home_team_id:Team.all[5], away_team_id:Team.all[24]},
  { week:2, home_team_id:Team.all[7], away_team_id:Team.all[2]},
  { week:2, home_team_id:Team.all[23], away_team_id:Team.all[1]},
  { week:2, home_team_id:Team.all[0], away_team_id:Team.all[29]},
  { week:2, home_team_id:Team.all[25], away_team_id:Team.all[6]},
  { week:2, home_team_id:Team.all[31], away_team_id:Team.all[8]},
  { week:2, home_team_id:Team.all[12], away_team_id:Team.all[15]},
  { week:2, home_team_id:Team.all[4], away_team_id:Team.all[27]},
  { week:2, home_team_id:Team.all[3], away_team_id:Team.all[22]},
  { week:2, home_team_id:Team.all[21], away_team_id:Team.all[20]},
  { week:2, home_team_id:Team.all[9], away_team_id:Team.all[13]},
  { week:2, home_team_id:Team.all[10], away_team_id:Team.all[30]},
  { week:2, home_team_id:Team.all[16], away_team_id:Team.all[28]},
  { week:2, home_team_id:Team.all[19], away_team_id:Team.all[17]},
  { week:2, home_team_id:Team.all[18], away_team_id:Team.all[11]},
  { week:2, home_team_id:Team.all[26], away_team_id:Team.all[14]},
  { week:3, home_team_id:Team.all[3], away_team_id:Team.all[0]},
  { week:3, home_team_id:Team.all[13], away_team_id:Team.all[26]},
  { week:3, home_team_id:Team.all[17], away_team_id:Team.all[7]},
  { week:3, home_team_id:Team.all[21], away_team_id:Team.all[31]},
  { week:3, home_team_id:Team.all[11], away_team_id:Team.all[10]},
  { week:3, home_team_id:Team.all[28], away_team_id:Team.all[27]},
  { week:3, home_team_id:Team.all[14], away_team_id:Team.all[2]},
  { week:3, home_team_id:Team.all[30], away_team_id:Team.all[23]},
  { week:3, home_team_id:Team.all[19], away_team_id:Team.all[12]},
  { week:3, home_team_id:Team.all[6], away_team_id:Team.all[9]},
  { week:3, home_team_id:Team.all[29], away_team_id:Team.all[16]},
  { week:3, home_team_id:Team.all[15], away_team_id:Team.all[22]},
  { week:3, home_team_id:Team.all[24], away_team_id:Team.all[25]},
  { week:3, home_team_id:Team.all[8], away_team_id:Team.all[5]},
  { week:3, home_team_id:Team.all[20], away_team_id:Team.all[1]},
  { week:3, home_team_id:Team.all[4], away_team_id:Team.all[18]},
  { week:4, home_team_id:Team.all[19], away_team_id:Team.all[3]},
  { week:4, home_team_id:Team.all[18], away_team_id:Team.all[21]},
  { week:4, home_team_id:Team.all[6], away_team_id:Team.all[17]},
  { week:4, home_team_id:Team.all[1], away_team_id:Team.all[4]},
  { week:4, home_team_id:Team.all[2], away_team_id:Team.all[23]},
  { week:4, home_team_id:Team.all[27], away_team_id:Team.all[8]},
  { week:4, home_team_id:Team.all[5], away_team_id:Team.all[10]},
  { week:4, home_team_id:Team.all[26], away_team_id:Team.all[20]},
  { week:4, home_team_id:Team.all[29], away_team_id:Team.all[9]},
  { week:4, home_team_id:Team.all[14], away_team_id:Team.all[13]},
  { week:4, home_team_id:Team.all[31], away_team_id:Team.all[7]},
  { week:4, home_team_id:Team.all[22], away_team_id:Team.all[28]},
  { week:4, home_team_id:Team.all[25], away_team_id:Team.all[15]},
  { week:4, home_team_id:Team.all[12], away_team_id:Team.all[30]},
  { week:4, home_team_id:Team.all[0], away_team_id:Team.all[16]},
  { week:5, home_team_id:Team.all[25], away_team_id:Team.all[22]},
  { week:5, home_team_id:Team.all[18], away_team_id:Team.all[12]},
  { week:5, home_team_id:Team.all[11], away_team_id:Team.all[21]},
  { week:5, home_team_id:Team.all[9], away_team_id:Team.all[1]},
  { week:5, home_team_id:Team.all[16], away_team_id:Team.all[3]},
  { week:5, home_team_id:Team.all[2], away_team_id:Team.all[31]},
  { week:5, home_team_id:Team.all[10], away_team_id:Team.all[24]},
  { week:5, home_team_id:Team.all[4], away_team_id:Team.all[29]},
  { week:5, home_team_id:Team.all[13], away_team_id:Team.all[5]},
  { week:5, home_team_id:Team.all[23], away_team_id:Team.all[26]},
  { week:5, home_team_id:Team.all[8], away_team_id:Team.all[6]},
  { week:5, home_team_id:Team.all[27], away_team_id:Team.all[0]},
  { week:5, home_team_id:Team.all[7], away_team_id:Team.all[19]},
  { week:5, home_team_id:Team.all[17], away_team_id:Team.all[30]},
  { week:6, home_team_id:Team.all[28], away_team_id:Team.all[1]},
  { week:6, home_team_id:Team.all[21], away_team_id:Team.all[2]},
  { week:6, home_team_id:Team.all[10], away_team_id:Team.all[16]},
  { week:6, home_team_id:Team.all[5], away_team_id:Team.all[14]},
  { week:6, home_team_id:Team.all[17], away_team_id:Team.all[25]},
  { week:6, home_team_id:Team.all[23], away_team_id:Team.all[15]},
  { week:6, home_team_id:Team.all[20], away_team_id:Team.all[4]},
  { week:6, home_team_id:Team.all[31], away_team_id:Team.all[24]},
  { week:6, home_team_id:Team.all[3], away_team_id:Team.all[27]},
  { week:6, home_team_id:Team.all[12], away_team_id:Team.all[13]},
  { week:6, home_team_id:Team.all[11], away_team_id:Team.all[8]},
  { week:6, home_team_id:Team.all[30], away_team_id:Team.all[7]},
  { week:6, home_team_id:Team.all[0], away_team_id:Team.all[22]},
  { week:6, home_team_id:Team.all[19], away_team_id:Team.all[6]},
  { week:6, home_team_id:Team.all[26], away_team_id:Team.all[9]},
  { week:7, home_team_id:Team.all[0], away_team_id:Team.all[28]},
  { week:7, home_team_id:Team.all[9], away_team_id:Team.all[12]},
  { week:7, home_team_id:Team.all[22], away_team_id:Team.all[2]},
  { week:7, home_team_id:Team.all[30], away_team_id:Team.all[13]},
  { week:7, home_team_id:Team.all[1], away_team_id:Team.all[26]},
  { week:7, home_team_id:Team.all[10], away_team_id:Team.all[31]},
  { week:7, home_team_id:Team.all[6], away_team_id:Team.all[7]},
  { week:7, home_team_id:Team.all[11], away_team_id:Team.all[5]},
  { week:7, home_team_id:Team.all[15], away_team_id:Team.all[20]},
  { week:7, home_team_id:Team.all[16], away_team_id:Team.all[21]},
  { week:7, home_team_id:Team.all[17], away_team_id:Team.all[3]},
  { week:7, home_team_id:Team.all[24], away_team_id:Team.all[18]},
  { week:7, home_team_id:Team.all[25], away_team_id:Team.all[19]},
  { week:7, home_team_id:Team.all[27], away_team_id:Team.all[29]},
  { week:7, home_team_id:Team.all[14], away_team_id:Team.all[23]},
  { week:8, home_team_id:Team.all[13], away_team_id:Team.all[15]},
  { week:8, home_team_id:Team.all[9], away_team_id:Team.all[26]},
  { week:8, home_team_id:Team.all[12], away_team_id:Team.all[10]},
  { week:8, home_team_id:Team.all[20], away_team_id:Team.all[28]},
  { week:8, home_team_id:Team.all[5], away_team_id:Team.all[18]},
  { week:8, home_team_id:Team.all[4], away_team_id:Team.all[0]},
  { week:8, home_team_id:Team.all[8], away_team_id:Team.all[24]},
  { week:8, home_team_id:Team.all[7], away_team_id:Team.all[22]},
  { week:8, home_team_id:Team.all[1], away_team_id:Team.all[11]},
  { week:8, home_team_id:Team.all[6], away_team_id:Team.all[31]},
  { week:8, home_team_id:Team.all[3], away_team_id:Team.all[19]},
  { week:8, home_team_id:Team.all[29], away_team_id:Team.all[23]},
  { week:8, home_team_id:Team.all[30], away_team_id:Team.all[14]},
  { week:9, home_team_id:Team.all[23], away_team_id:Team.all[9]},
  { week:9, home_team_id:Team.all[26], away_team_id:Team.all[30]},
  { week:9, home_team_id:Team.all[29], away_team_id:Team.all[1]},
  { week:9, home_team_id:Team.all[2], away_team_id:Team.all[25]},
  { week:9, home_team_id:Team.all[7], away_team_id:Team.all[8]},
  { week:9, home_team_id:Team.all[27], away_team_id:Team.all[20]},
  { week:9, home_team_id:Team.all[16], away_team_id:Team.all[4]},
  { week:9, home_team_id:Team.all[17], away_team_id:Team.all[22]},
  { week:9, home_team_id:Team.all[18], away_team_id:Team.all[10]},
  { week:9, home_team_id:Team.all[28], away_team_id:Team.all[3]},
  { week:9, home_team_id:Team.all[21], away_team_id:Team.all[24]},
  { week:9, home_team_id:Team.all[15], away_team_id:Team.all[14]},
  { week:9, home_team_id:Team.all[11], away_team_id:Team.all[13]},
  { week:10, home_team_id:Team.all[19], away_team_id:Team.all[28]},
  { week:10, home_team_id:Team.all[26], away_team_id:Team.all[17]},
  { week:10, home_team_id:Team.all[31], away_team_id:Team.all[18]},
  { week:10, home_team_id:Team.all[25], away_team_id:Team.all[8]},
  { week:10, home_team_id:Team.all[22], away_team_id:Team.all[16]},
  { week:10, home_team_id:Team.all[0], away_team_id:Team.all[27]},
  { week:10, home_team_id:Team.all[4], away_team_id:Team.all[15]},
  { week:10, home_team_id:Team.all[24], away_team_id:Team.all[1]},
  { week:10, home_team_id:Team.all[2], away_team_id:Team.all[7]},
  { week:10, home_team_id:Team.all[30], away_team_id:Team.all[11]},
  { week:10, home_team_id:Team.all[14], away_team_id:Team.all[12]},
  { week:10, home_team_id:Team.all[20], away_team_id:Team.all[9]},
  { week:10, home_team_id:Team.all[29], away_team_id:Team.all[5]},
  { week:10, home_team_id:Team.all[21], away_team_id:Team.all[6]},
  { week:11, home_team_id:Team.all[28], away_team_id:Team.all[24]},
  { week:11, home_team_id:Team.all[7], away_team_id:Team.all[25]},
  { week:11, home_team_id:Team.all[31], away_team_id:Team.all[11]},
  { week:11, home_team_id:Team.all[18], away_team_id:Team.all[0]},
  { week:11, home_team_id:Team.all[6], away_team_id:Team.all[3]},
  { week:11, home_team_id:Team.all[27], away_team_id:Team.all[19]},
  { week:11, home_team_id:Team.all[8], away_team_id:Team.all[2]},
  { week:11, home_team_id:Team.all[23], away_team_id:Team.all[12]},
  { week:11, home_team_id:Team.all[4], away_team_id:Team.all[20]},
  { week:11, home_team_id:Team.all[10], away_team_id:Team.all[14]},
  { week:11, home_team_id:Team.all[16], away_team_id:Team.all[17]},
  { week:11, home_team_id:Team.all[15], away_team_id:Team.all[29]},
  { week:11, home_team_id:Team.all[13], away_team_id:Team.all[30]},
  { week:11, home_team_id:Team.all[21], away_team_id:Team.all[5]},
  { week:12, home_team_id:Team.all[22], away_team_id:Team.all[19]},
  { week:12, home_team_id:Team.all[24], away_team_id:Team.all[11]},
  { week:12, home_team_id:Team.all[1], away_team_id:Team.all[0]},
  { week:12, home_team_id:Team.all[20], away_team_id:Team.all[16]},
  { week:12, home_team_id:Team.all[9], away_team_id:Team.all[15]},
  { week:12, home_team_id:Team.all[12], away_team_id:Team.all[26]},
  { week:12, home_team_id:Team.all[8], away_team_id:Team.all[31]},
  { week:12, home_team_id:Team.all[2], away_team_id:Team.all[6]},
  { week:12, home_team_id:Team.all[3], away_team_id:Team.all[14]},
  { week:12, home_team_id:Team.all[29], away_team_id:Team.all[28]},
  { week:12, home_team_id:Team.all[17], away_team_id:Team.all[27]},
  { week:12, home_team_id:Team.all[7], away_team_id:Team.all[21]},
  { week:12, home_team_id:Team.all[23], away_team_id:Team.all[4]},
  { week:12, home_team_id:Team.all[5], away_team_id:Team.all[30]},
  { week:12, home_team_id:Team.all[10], away_team_id:Team.all[18]},
  { week:12, home_team_id:Team.all[13], away_team_id:Team.all[25]},
  { week:13, home_team_id:Team.all[22], away_team_id:Team.all[13]},
  { week:13, home_team_id:Team.all[0], away_team_id:Team.all[31]},
  { week:13, home_team_id:Team.all[14], away_team_id:Team.all[9]},
  { week:13, home_team_id:Team.all[2], away_team_id:Team.all[17]},
  { week:13, home_team_id:Team.all[11], away_team_id:Team.all[12]},
  { week:13, home_team_id:Team.all[1], away_team_id:Team.all[15]},
  { week:13, home_team_id:Team.all[5], away_team_id:Team.all[27]},
  { week:13, home_team_id:Team.all[23], away_team_id:Team.all[3]},
  { week:13, home_team_id:Team.all[6], away_team_id:Team.all[24]},
  { week:13, home_team_id:Team.all[26], away_team_id:Team.all[29]},
  { week:13, home_team_id:Team.all[19], away_team_id:Team.all[16]},
  { week:13, home_team_id:Team.all[25], away_team_id:Team.all[21]},
  { week:13, home_team_id:Team.all[18], away_team_id:Team.all[8]},
  { week:13, home_team_id:Team.all[20], away_team_id:Team.all[10]},
  { week:13, home_team_id:Team.all[28], away_team_id:Team.all[4]},
  { week:14, home_team_id:Team.all[19], away_team_id:Team.all[2]},
  { week:14, home_team_id:Team.all[24], away_team_id:Team.all[31]},
  { week:14, home_team_id:Team.all[11], away_team_id:Team.all[28]},
  { week:14, home_team_id:Team.all[17], away_team_id:Team.all[0]},
  { week:14, home_team_id:Team.all[29], away_team_id:Team.all[20]},
  { week:14, home_team_id:Team.all[30], away_team_id:Team.all[9]},
  { week:14, home_team_id:Team.all[15], away_team_id:Team.all[23]},
  { week:14, home_team_id:Team.all[16], away_team_id:Team.all[1]},
  { week:14, home_team_id:Team.all[10], away_team_id:Team.all[5]},
  { week:14, home_team_id:Team.all[27], away_team_id:Team.all[22]},
  { week:14, home_team_id:Team.all[21], away_team_id:Team.all[8]},
  { week:14, home_team_id:Team.all[3], away_team_id:Team.all[25]},
  { week:14, home_team_id:Team.all[4], away_team_id:Team.all[26]},
  { week:14, home_team_id:Team.all[14], away_team_id:Team.all[18]},
  { week:14, home_team_id:Team.all[13], away_team_id:Team.all[12]},
  { week:14, home_team_id:Team.all[7], away_team_id:Team.all[6]},
  { week:15, home_team_id:Team.all[18], away_team_id:Team.all[13]},
  { week:15, home_team_id:Team.all[21], away_team_id:Team.all[10]},
  { week:15, home_team_id:Team.all[6], away_team_id:Team.all[25]},
  { week:15, home_team_id:Team.all[28], away_team_id:Team.all[16]},
  { week:15, home_team_id:Team.all[15], away_team_id:Team.all[30]},
  { week:15, home_team_id:Team.all[0], away_team_id:Team.all[20]},
  { week:15, home_team_id:Team.all[31], away_team_id:Team.all[4]},
  { week:15, home_team_id:Team.all[2], away_team_id:Team.all[24]},
  { week:15, home_team_id:Team.all[5], away_team_id:Team.all[11]},
  { week:15, home_team_id:Team.all[12], away_team_id:Team.all[14]},
  { week:15, home_team_id:Team.all[9], away_team_id:Team.all[19]},
  { week:15, home_team_id:Team.all[1], away_team_id:Team.all[27]},
  { week:15, home_team_id:Team.all[26], away_team_id:Team.all[23]},
  { week:15, home_team_id:Team.all[22], away_team_id:Team.all[17]},
  { week:15, home_team_id:Team.all[3], away_team_id:Team.all[7]},
  { week:15, home_team_id:Team.all[8], away_team_id:Team.all[29]},
  { week:16, home_team_id:Team.all[11], away_team_id:Team.all[18]},
  { week:16, home_team_id:Team.all[20], away_team_id:Team.all[29]},
  { week:16, home_team_id:Team.all[4], away_team_id:Team.all[1]},
  { week:16, home_team_id:Team.all[5], away_team_id:Team.all[31]},
  { week:16, home_team_id:Team.all[14], away_team_id:Team.all[30]},
  { week:16, home_team_id:Team.all[19], away_team_id:Team.all[22]},
  { week:16, home_team_id:Team.all[24], away_team_id:Team.all[21]},
  { week:16, home_team_id:Team.all[15], away_team_id:Team.all[9]},
  { week:16, home_team_id:Team.all[25], away_team_id:Team.all[2]},
  { week:16, home_team_id:Team.all[28], away_team_id:Team.all[0]},
  { week:16, home_team_id:Team.all[16], away_team_id:Team.all[27]},
  { week:16, home_team_id:Team.all[12], away_team_id:Team.all[6]},
  { week:16, home_team_id:Team.all[7], away_team_id:Team.all[26]},
  { week:16, home_team_id:Team.all[23], away_team_id:Team.all[13]},
  { week:16, home_team_id:Team.all[8], away_team_id:Team.all[10]},
  { week:16, home_team_id:Team.all[3], away_team_id:Team.all[17]},
  { week:17, home_team_id:Team.all[25], away_team_id:Team.all[7]},
  { week:17, home_team_id:Team.all[18], away_team_id:Team.all[5]},
  { week:17, home_team_id:Team.all[17], away_team_id:Team.all[19]},
  { week:17, home_team_id:Team.all[6], away_team_id:Team.all[2]},
  { week:17, home_team_id:Team.all[29], away_team_id:Team.all[4]},
  { week:17, home_team_id:Team.all[30], away_team_id:Team.all[12]},
  { week:17, home_team_id:Team.all[16], away_team_id:Team.all[0]},
  { week:17, home_team_id:Team.all[31], away_team_id:Team.all[21]},
  { week:17, home_team_id:Team.all[24], away_team_id:Team.all[8]},
  { week:17, home_team_id:Team.all[1], away_team_id:Team.all[20]},
  { week:17, home_team_id:Team.all[22], away_team_id:Team.all[3]},
  { week:17, home_team_id:Team.all[9], away_team_id:Team.all[23]},
  { week:17, home_team_id:Team.all[13], away_team_id:Team.all[14]},
  { week:17, home_team_id:Team.all[27], away_team_id:Team.all[28]},
  { week:17, home_team_id:Team.all[26], away_team_id:Team.all[15]},
  { week:17, home_team_id:Team.all[10], away_team_id:Team.all[11]}
  ])

# a = Team.first
# b = Team.last

# Matchup.create({:winner => a, :loser   => b, :home_team_id => a, :away_team_id => b})

puts "created #{Team.count} teams"
puts "created #{Matchup.count} matchups"
puts "created #{User.count} users"

